= Christian / Cristiano

Nexo de información sobre temas cristianos: teología, estudios bíblicos, devocionales...

link:Bookrecommends.adoc[Book recommendations]

== Theology / Teología

=== Cristología

Jesús es el Dios de Israel, al mismo tiempo siendo el máximo y mejor ejemplo de la humanidad; el único que por sí pudo cumplir el propósito original de la humanidad. 

=== Exilio

El exilio babilónico fue un evento determinante en la historia bíblica. Los "profetas" - aquellos que editaron y tejieron la Biblia Hebrea, tuvieron una perspectiva de exilio en todo lo que escribe. Por eso, en la Biblia vemos que Adán y Eva fueron exiliados hacia el este (... insert Biblical quotation ...), hacia donde estaba Babilonia. 

El exilio, en especial la exhortación de Jeremías de cómo vivir, debe servirnos de ejemplo sobre cómo vivir en este mundo, no suscribiéndonos a un nacionalismo por el país en que estamos o esta tierra, pero sí velando por su prosperidad, mientras que a la vez resistimos sus costumbres, sin violencia pero sin conformarnos, manteniendo los valores del Reino de Dios, mientras esperamos su regreso. 

Recurso: *A Biblical Theology of Exile* de _Daniel L. Smith Christopher._

== Biblical Studies / Estudios Bíblicos


